pluginManagement {
    repositories {
        mavenCentral()
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.architectury.dev/' }
        maven { url = 'https://maven.neoforged.net/releases' }
        gradlePluginPortal()
    }
}

def configProps = new Properties()
def propsFile = file('config/gradle.properties')
if (propsFile.exists()) {
    propsFile.withInputStream { configProps.load(it) }
    configProps.each { key, value ->
        gradle.ext.set(key.toString(), value.toString())
    }
}

rootProject.name = 'Advanced-Economics'

include 'common'
include 'fabric'
include 'neoforge'
