# Mod Information
mod_id=advanced_economics
mod_name=Advanced Economics
mod_version=0.1
mod_group=com.example.advancedeconomics
mod_version_type=dev

# Environment
minecraft_version=1.20.4
fabric_loader_version=0.15.7
neoforge_version=20.4.80-beta

# UI Lib Dependency (Modrinth)
# Page: https://modrinth.com/mod/ui-lib
ui_lib_version=1.0.0
ui_lib_modrinth_slug=ui-lib
