# Mod Information
mod_id=advanced_economics
mod_name=Advanced Economics
mod_version=0.6
mod_group=com.example.advancedeconomics
mod_version_type=dev

# Environment
minecraft_version=26.2
fabric_loader_version=0.19.3
neoforge_version=20.4.80-beta

# UI Lib Dependency (Modrinth)
# Page: https://modrinth.com/mod/ui-lib
ui_lib_version=21.1.1
ui_lib_modrinth_slug=ui-lib
